package client;

import java.awt.Color;
import java.awt.Point;

/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
/**
 *
 * @author Chale
 */
public class DsLibraryMain extends javax.swing.JFrame {

    /**
     * Creates new form ILS_Main
     */
    public DsLibraryMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        mnuLibraries = new javax.swing.JMenu();
        mnuiAddLibrary = new javax.swing.JMenuItem();
        mnuiViewLibrary = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnuiNewRule = new javax.swing.JMenuItem();
        mnuiViewRule = new javax.swing.JMenuItem();
        mnuiShelves = new javax.swing.JMenuItem();
        mnuPatron = new javax.swing.JMenu();
        mnuiNewPatron = new javax.swing.JMenuItem();
        mnuiPatronSearch = new javax.swing.JMenuItem();
        mnuCataloging = new javax.swing.JMenu();
        mnuiBiblioRecord = new javax.swing.JMenuItem();
        mnuiUpdateQuantity = new javax.swing.JMenuItem();
        mnuicatalogueSearch = new javax.swing.JMenuItem();
        mnuCirculation = new javax.swing.JMenu();
        mnuiCheckIn = new javax.swing.JMenuItem();
        mnuiCheckOut = new javax.swing.JMenuItem();
        mnuAccount = new javax.swing.JMenu();
        mnuiAddUser = new javax.swing.JMenuItem();
        mnuiChangePassword = new javax.swing.JMenuItem();
        mnuiManageUser = new javax.swing.JMenuItem();
        mnuiLogin = new javax.swing.JMenuItem();
        mnuSetting = new javax.swing.JMenu();
        mnuiAddServer = new javax.swing.JMenuItem();
        mnuReport = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Distributed Library System Client");
        setBackground(new java.awt.Color(153, 153, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        desktopPane.setBackground(new java.awt.Color(153, 153, 255));

        menuBar.setBackground(new java.awt.Color(204, 204, 255));

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");
        fileMenu.setToolTipText("");

        openMenuItem.setBackground(new java.awt.Color(204, 204, 255));
        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setBackground(new java.awt.Color(204, 204, 255));
        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setBackground(new java.awt.Color(204, 204, 255));
        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setBackground(new java.awt.Color(204, 204, 255));
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        mnuLibraries.setMnemonic('l');
        mnuLibraries.setText("Library");
        mnuLibraries.setToolTipText("");

        mnuiAddLibrary.setText("Add New Library");
        mnuiAddLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiAddLibraryActionPerformed(evt);
            }
        });
        mnuLibraries.add(mnuiAddLibrary);

        mnuiViewLibrary.setText("View Libraries");
        mnuiViewLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiViewLibraryActionPerformed(evt);
            }
        });
        mnuLibraries.add(mnuiViewLibrary);

        jMenu1.setText("Rules");

        mnuiNewRule.setText("Add New Rule");
        mnuiNewRule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiNewRuleActionPerformed(evt);
            }
        });
        jMenu1.add(mnuiNewRule);

        mnuiViewRule.setText("View Rules");
        mnuiViewRule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiViewRuleActionPerformed(evt);
            }
        });
        jMenu1.add(mnuiViewRule);

        mnuLibraries.add(jMenu1);

        mnuiShelves.setText("Shelves");
        mnuiShelves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiShelvesActionPerformed(evt);
            }
        });
        mnuLibraries.add(mnuiShelves);

        menuBar.add(mnuLibraries);

        mnuPatron.setMnemonic('p');
        mnuPatron.setText("Patron");

        mnuiNewPatron.setText("New Patron");
        mnuiNewPatron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiNewPatronActionPerformed(evt);
            }
        });
        mnuPatron.add(mnuiNewPatron);

        mnuiPatronSearch.setText("Search");
        mnuiPatronSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiPatronSearchActionPerformed(evt);
            }
        });
        mnuPatron.add(mnuiPatronSearch);

        menuBar.add(mnuPatron);

        mnuCataloging.setMnemonic('c');
        mnuCataloging.setText("Cataloging");

        mnuiBiblioRecord.setText("New Record");
        mnuiBiblioRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiBiblioRecordActionPerformed(evt);
            }
        });
        mnuCataloging.add(mnuiBiblioRecord);

        mnuiUpdateQuantity.setText("Update Quantity");
        mnuiUpdateQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiUpdateQuantityActionPerformed(evt);
            }
        });
        mnuCataloging.add(mnuiUpdateQuantity);

        mnuicatalogueSearch.setText("Search");
        mnuicatalogueSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuicatalogueSearchActionPerformed(evt);
            }
        });
        mnuCataloging.add(mnuicatalogueSearch);

        menuBar.add(mnuCataloging);

        mnuCirculation.setMnemonic('i');
        mnuCirculation.setText("Circulation");

        mnuiCheckIn.setText("Check In");
        mnuiCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiCheckInActionPerformed(evt);
            }
        });
        mnuCirculation.add(mnuiCheckIn);

        mnuiCheckOut.setText("Check Out");
        mnuiCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiCheckOutActionPerformed(evt);
            }
        });
        mnuCirculation.add(mnuiCheckOut);

        menuBar.add(mnuCirculation);

        mnuAccount.setMnemonic('a');
        mnuAccount.setText("Account");

        mnuiAddUser.setText("New Account");
        mnuiAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiAddUserActionPerformed(evt);
            }
        });
        mnuAccount.add(mnuiAddUser);

        mnuiChangePassword.setText("Change Password");
        mnuAccount.add(mnuiChangePassword);

        mnuiManageUser.setText("Manage User");
        mnuAccount.add(mnuiManageUser);

        mnuiLogin.setText("Log In");
        mnuiLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiLoginActionPerformed(evt);
            }
        });
        mnuAccount.add(mnuiLogin);

        menuBar.add(mnuAccount);

        mnuSetting.setMnemonic('s');
        mnuSetting.setText("Setting");

        mnuiAddServer.setText("Add Server");
        mnuiAddServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiAddServerActionPerformed(evt);
            }
        });
        mnuSetting.add(mnuiAddServer);

        menuBar.add(mnuSetting);

        mnuReport.setMnemonic('r');
        mnuReport.setText("Report");
        menuBar.add(mnuReport);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1096, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1112, 681));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loggedIn();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        loggedIn();
    }//GEN-LAST:event_formWindowActivated

    private void mnuiAddServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiAddServerActionPerformed
        // TODO add your handling code here:
        DlgAddServerInfo dlg = new DlgAddServerInfo(this, true);
        //*************dunamic login form locatio *******************//
        Point p = this.getLocation();
        int x = (int) p.getX();
        int y = (int) p.getY();
        int w=this.getWidth();
        x = x + w/2-220;
        y = y + 80;
        p.setLocation(x, y);
        //********************************************************//
        dlg.setLocation(p);
        dlg.setVisible(true);
    }//GEN-LAST:event_mnuiAddServerActionPerformed

    private void mnuiLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiLoginActionPerformed
        if (UserLogin.loggedin) {
            mnuAccount.setForeground(Color.blue);
            DlgConfirmLogOut lgo = new DlgConfirmLogOut(this, true);
            //*************dunamic login form location *******************//
            Point p = this.getLocation();
            int x = (int) p.getX();
            int y = (int) p.getY();
            x = x + 305;
            y = y + 52;
            p.setLocation(x, y);
            //********************************************************//
            lgo.setLocation(p);
            lgo.setVisible(true);

        } else {
            mnuAccount.setForeground(Color.blue);
            DlgLogin dlg = new DlgLogin(this, true);
            //*************dunamic login form location *******************//
            Point p = this.getLocation();
            int x = (int) p.getX();
            int y = (int) p.getY();
            x = x + 305;
            y = y + 52;
            p.setLocation(x, y);
            //********************************************************//
            dlg.setLocation(p);
            dlg.setVisible(true);
        }
    }//GEN-LAST:event_mnuiLoginActionPerformed

    private void mnuiAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiAddUserActionPerformed
        FrmCreateUser cuser = new FrmCreateUser(this, true);
        cuser.setVisible(true);
    }//GEN-LAST:event_mnuiAddUserActionPerformed

    private void mnuiAddLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiAddLibraryActionPerformed
        FrmAddLibrary lib = new FrmAddLibrary(this, true);
        lib.setVisible(true);
    }//GEN-LAST:event_mnuiAddLibraryActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void mnuiViewLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiViewLibraryActionPerformed
        FrmViewLibrary interFrame = new FrmViewLibrary();
        desktopPane.add(interFrame);
        interFrame.setVisible(true);
        interFrame.toFront();
    }//GEN-LAST:event_mnuiViewLibraryActionPerformed

    private void mnuicatalogueSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuicatalogueSearchActionPerformed
        FrmSearch interFrame = new FrmSearch();
        desktopPane.add(interFrame);
        interFrame.setVisible(true);
        interFrame.toFront();
    }//GEN-LAST:event_mnuicatalogueSearchActionPerformed

    private void mnuiViewRuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiViewRuleActionPerformed
        FrmViewRule interFrame = new FrmViewRule();
        desktopPane.add(interFrame);
        interFrame.setVisible(true);
        interFrame.toFront();
    }//GEN-LAST:event_mnuiViewRuleActionPerformed

    private void mnuiShelvesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiShelvesActionPerformed
        FrmShelf shel = new FrmShelf(this, true);
        shel.setVisible(true);
    }//GEN-LAST:event_mnuiShelvesActionPerformed

    private void mnuiNewRuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiNewRuleActionPerformed
        FrmAddRule rule = new FrmAddRule(this, true);
        rule.setVisible(true);
    }//GEN-LAST:event_mnuiNewRuleActionPerformed

    private void mnuiPatronSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiPatronSearchActionPerformed
        FrmPatronList interFrame = new FrmPatronList();
        desktopPane.add(interFrame);
        interFrame.setVisible(true);
        interFrame.toFront();
    }//GEN-LAST:event_mnuiPatronSearchActionPerformed

    private void mnuiNewPatronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiNewPatronActionPerformed
        FrmAddPatron pat = new FrmAddPatron(this, true);
        pat.setVisible(true);
    }//GEN-LAST:event_mnuiNewPatronActionPerformed

    private void mnuiBiblioRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiBiblioRecordActionPerformed
        FrmBiblioRecord rec = new FrmBiblioRecord(this, true);
        rec.setVisible(true);
    }//GEN-LAST:event_mnuiBiblioRecordActionPerformed

    private void mnuiCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiCheckOutActionPerformed
        FrmCheckOut chk = new FrmCheckOut(this, true);
        chk.setVisible(true);
    }//GEN-LAST:event_mnuiCheckOutActionPerformed

    private void mnuiUpdateQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiUpdateQuantityActionPerformed
        FrmQuantity chk = new FrmQuantity(this, true);
        chk.setVisible(true);
    }//GEN-LAST:event_mnuiUpdateQuantityActionPerformed

    private void mnuiCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiCheckInActionPerformed
        FrmCheckIn in = new FrmCheckIn(this, true);
        in.setVisible(true);
    }//GEN-LAST:event_mnuiCheckInActionPerformed

    //////////////////****************methods********************/////////////////////////
    private void loggedIn() {
        if (UserLogin.loggedin) {
            mnuAccount.setForeground(Color.black);
           
            mnuiAddLibrary.setEnabled(true);
            //mnuiViewRule.setEnabled(true);
            mnuiNewRule.setEnabled(true);
            mnuiShelves.setEnabled(true);
            
            mnuPatron.setEnabled(true);
            mnuiBiblioRecord.setEnabled(true);
            mnuiUpdateQuantity.setEnabled(true);
            
            mnuCirculation.setEnabled(true);
            mnuiCheckIn.setEnabled(true);
            mnuiCheckOut.setEnabled(true);
            
            mnuiAddUser.setEnabled(true);
            mnuiChangePassword.setEnabled(true);
            mnuiManageUser.setEnabled(true);           
            mnuReport.setEnabled(true);

            mnuiLogin.setText("Log Out");
        } else {
            mnuAccount.setForeground(Color.black);
          
            mnuiAddLibrary.setEnabled(false);
            //mnuiViewRule.setEnabled(false);
            mnuiNewRule.setEnabled(false);
            mnuiShelves.setEnabled(false);

            mnuPatron.setEnabled(false);
            mnuiBiblioRecord.setEnabled(false);
            mnuiUpdateQuantity.setEnabled(false);
            
            mnuCirculation.setEnabled(false);
            mnuiCheckIn.setEnabled(false);
            mnuiCheckOut.setEnabled(false);
            
            mnuiAddUser.setEnabled(false);
            mnuiChangePassword.setEnabled(false);
            mnuiManageUser.setEnabled(false);            
            mnuReport.setEnabled(false);

            mnuiLogin.setText("Log In");
        }
    }

    /////////////// ********************************************//////////////////////////
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DsLibraryMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DsLibraryMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DsLibraryMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DsLibraryMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new DsLibraryMain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuAccount;
    private javax.swing.JMenu mnuCataloging;
    private javax.swing.JMenu mnuCirculation;
    private javax.swing.JMenu mnuLibraries;
    private javax.swing.JMenu mnuPatron;
    private javax.swing.JMenu mnuReport;
    private javax.swing.JMenu mnuSetting;
    private javax.swing.JMenuItem mnuiAddLibrary;
    private javax.swing.JMenuItem mnuiAddServer;
    private javax.swing.JMenuItem mnuiAddUser;
    private javax.swing.JMenuItem mnuiBiblioRecord;
    private javax.swing.JMenuItem mnuiChangePassword;
    private javax.swing.JMenuItem mnuiCheckIn;
    private javax.swing.JMenuItem mnuiCheckOut;
    private javax.swing.JMenuItem mnuiLogin;
    private javax.swing.JMenuItem mnuiManageUser;
    private javax.swing.JMenuItem mnuiNewPatron;
    private javax.swing.JMenuItem mnuiNewRule;
    private javax.swing.JMenuItem mnuiPatronSearch;
    private javax.swing.JMenuItem mnuiShelves;
    private javax.swing.JMenuItem mnuiUpdateQuantity;
    private javax.swing.JMenuItem mnuiViewLibrary;
    private javax.swing.JMenuItem mnuiViewRule;
    private javax.swing.JMenuItem mnuicatalogueSearch;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables
}
